### PR TITLE
Update PVGrun to 1.04.

### PR DESCRIPTION
**Pull request by JamesBromberger**
Update PVGrub to 1.04 to support xv compressed kernels (paving the way for Jessie). http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/UserProvidedKernels.html

### CODE REVIEW

**Comment by andsens** [comment]
I don't think this PR contains the changes you intended James, you just deleted a file...?

**Comment by JamesBromberger** [comment]
There was a temp file that iaccidentally checked in, and the ec2/amis.py file sjoild be updated... will check in 10 mins...

-- 
Written on a phone; please excuse typos! Call +61 422 166 708 if the above is garbled beyond recognition or really really funny autocorrect!  :)

-------- Original message --------

**Comment by JamesBromberger** [comment]
You're right - should be there now....

**Comment by andsens** [comment]
There's some indentation inconsistency in the manifest, also: could you rebase so that we have one commit for changing the manifest and one for changing the kernel IDs?

**Comment by andsens** [comment]
This has been fixed.

**Pull request closed without merging**
