### PR TITLE
Use /etc/sudoers.d/ to configure admin user sudo rights

### LINKED ISSUE #43: Please use /etc/sudoers.d to give superuser rights to the default user.
Hi Anders,

Could you change plugins/admin-user-tasks/create-user to drop a configuration file in /etc/sudoers.d instead of modifying /etc/sudoers directly ?  This will make smoother upgrades each time /etc/sudoers is modified by upgrade of the sudo package.  Here is an example from Ubuntu, where the default account is "ubuntu".

```
root@ip-10-148-5-107:/etc# cat sudoers.d/90-cloudimg-ubuntu 
# ubuntu user is default user in cloud-images.
# It needs passwordless sudo functionality.
ubuntu ALL=(ALL) NOPASSWD:ALL
```

Cheers,
## 

Charles Plessy
Tsurumi, Kanagawa, Japan

### PR DESCRIPTION
**Pull request by tmatilai**
Maybe something like this to fix #43?

This PR is based on master even though I couldn't get the master branch to work. But I tested it on top of 'offical-6.0.6-2012/20/11' tag and that seemed to work as expected.

This _should_ also work on Wheezy (#41).

### CODE REVIEW

**Comment by tmatilai** [comment]
I tested also by creating Wheezy using the "dev" branch with this and #44 merged and seemed to work as expected.

Thanks for the project! Great work! =)

**Comment by andsens** [comment]
I will try to merge it tonight, it got a bit late yesterday. Thank you for testing it and thank you for the patch, it's great to see some pull requests coming in :-)

**Comment by tmatilai** [comment]
No hurry, I already have my Wheezy AMI. =)
After all my patches I still failed to create a working Squeeze image from the dev/master branch, but I didn't have time to investigate further.

**Comment by andsens** [comment]
Looks good, but I meant that the `includedir /etc/sudoers.d` was actually _disabled_ on squeeze, but I am already doing the changes myself, no worries. This great work, thanks!

**Comment by tmatilai** [comment]
No, it is _not_ disabled. The "includedir" directive really has to start with a '#' (to keep compatibility with older sudo versions for sure). Check the sudoers man page.

**Comment by andsens** [comment]
I am sorry, you're right! I just checked the man page. Well... that is not confusing _at all_.

**Comment by tmatilai** [comment]
Yeah, been there. =)

**Comment by andsens** [comment]
Both your pull request worked like a charm, thanks! I cherry-picked your commits, so I am just closing them here.

**Comment by tmatilai** [comment]
Cool, thanks! Tiny contributions for a great project. Keep up the good work! =)

**Pull request closed without merging**
