### PR TITLE
Changed imagedir in script

### PR DESCRIPTION
**Pull request by kenshaw**
I was having problems generating / testing AMI generation due to problems with unmounting (I have a bunch of complex [private] plugins I'm writing to create initial AMIs for my company). I changed the script so that instead of providing it an --imagedir parameter to change the ELB mount location, it now can be provided an optional --debootstrap-dir parameter (with a default of /target) which then combines that with the generated EC2 volume_id. 

I also cleaned up the --help documentation on the command, and updated the README.md to reflect the earlier changes.

### CODE REVIEW

**Comment by andsens** [comment]
Your changes to the help menu and the imagedir make a lot of sense.
Mounting it this way allows for parallel bootstrapping of different AMIs.  
Is there any reason to use `/target` instead of `/mount` as a default? The `/target` dir needs to be created first, while `/mnt` is meant for these kind of mounts, no?  
How about simply calling it bootstrap dir?

**Comment by kenshaw** [comment]
/target comes from the debootstrap world. Not really a big deal ;)

-Ken

**Comment by andsens** [comment]
Since `/target` doesn't exist per default, I would say we need a `mkdir -p` somewhere.
The script will not work out of the box otherwise, correct?

**Comment by kenshaw** [comment]
There's already a mkdir -p $imagedir ...

-Ken

**Comment by kenshaw** [comment]
Specifically, just to clarify, it's in tasks/10-create-volume ...

-Ken

**Comment by andsens** [comment]
oh, right. totally forgot about that. I'll merge tonight or tomorrow, probably going to rebase it about, squash some commits (typos etc.)

**Pull request closed without merging**
